### ISSUE TITLE
"ValueError: no gas strategy selected!" when Auto-disputing

### ISSUE THREAD

**Issue by 0xSpuddy** [tellor-io/disputable-values-monitor#142]
Was submitted a bad value on sepolia this morning and noticed that the Auto-disputer didn't dispute. Here's the traceback from the log:

Versions: 
telliot-core==0.2.7
telliot-feeds==0.1.11

```
Disputable Values Monitor 📒🔎📲
...Now with auto-disputing!
Alert sent!
Error decoding JSON from ethgasstation API
Error decoding JSON from ethgasstation API
Traceback (most recent call last):
  File "/home/ubuntu/disputable-values-monitor/denv/bin/cli", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/disputable-values-monitor/denv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/disputable-values-monitor/denv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/disputable-values-monitor/denv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/disputable-values-monitor/denv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/disputable-values-monitor/denv/lib/python3.9/site-packages/telliot_core/cli/utils.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 61, in main
    await start(
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 162, in start
    success_msg = await dispute(cfg, disp_cfg, account, new_report)
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/disputer.py", line 105, in dispute
    tx_receipt, status = await token.write(
  File "/home/ubuntu/disputable-values-monitor/denv/lib/python3.9/site-packages/telliot_core/contract/contract.py", line 115, in write
    raise ValueError("no gas strategy selected!")
ValueError: no gas strategy selected!
```

Let me know if more information is needed!

**Comment by 0xSpuddy** [comment]
fixed with recent PR
