### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#18]
Log:

```
Disputable Values Monitor 📒🔎📲
|    |       When | Transaction                                                                                          | Asset   | Currency   |        Value | Disputable                                                                              |
|---:|-----------:|:-----------------------------------------------------------------------------------------------------|:--------|:-----------|-------------:|:----------------------------------------------------------------------------------------|
|  0 | 1650649286 | https://rinkeby.etherscan.io/tx/0x58d36348d2e40675b8dc0605619cdd6a2e9c0d51b360c949e5c7f62a9d0aafa9   | BCT     | USD        |     3.43431  | ❗unsupported query ID: 35e083af947a4cf3bc053440c3b4f753433c76acab6c8b1911ee808104b72e85 |
|  1 | 1650649341 | https://mumbai.polygonscan.com/tx/0xf34302a072f5bdbde8220b33fe8d66f4628f216ad7eb14cc62ba3da93024bd69 | MATIC   | USD        |     1.4161   | ❗unsupported query ID: 40aa71e5205fdc7bdb7d65f7ae41daca3820c5d3a8f62357a99eda3aa27244a3 |
|  2 | 1650650651 | https://rinkeby.etherscan.io/tx/0x15131264fd5ae187cb8bb266822e04d6a0f778ca0e3043acbfafece26be6dd73   | TRB     | USD        |    19.95     | no ✔️                                                                                   |
|  3 | 1650650651 | https://rinkeby.etherscan.io/tx/0x2138bcd493e40eb56df53edf39336fcbeaafc35a19569bf0aeb56d0800bf1f00   | MKR     | USD        |  1735.79     | ❗unsupported query ID: b9d5e25dabd5f0a48f45f5b6b524bac100df05eaf5311f3e5339ac7c3dd0a37e |
|  4 | 1650651081 | https://mumbai.polygonscan.com/tx/0x2bd9e59c408dd7348bd91522eab1b1ca6cb302e620c8e8f484ac329a220dcdf1 | BTC     | USD        | 39302.9      | no ✔️                                                                                   |
|  5 | 1650652529 | https://mumbai.polygonscan.com/tx/0x2ba93879243d230d481728a4d9caab193df661f3462e669d529917b69bbec73e | RIC     | USD        |     0.141629 | ❗unsupported query ID: 6e5122118ce52cc9b97c359c1f174a3c21c71d810f7addce3484cc28e0be0f29 |
|  6 | 1650652820 | https://mumbai.polygonscan.com/tx/0xc1af37cb8c6ecbc8eed04121313bc8770178655d4c27651161dac23263290711 | RIC     | USD        |     0.126783 | ❗unsupported query ID: 6e5122118ce52cc9b97c359c1f174a3c21c71d810f7addce3484cc28e0be0f29 |
|  7 | 1650654560 | https://mumbai.polygonscan.com/tx/0xfe5d3c6b141e12c00c45e2431df07b9ed686fa3e0c476b699de44d00b8c31633 | MKR     | USD        |  1735.44     | ❗unsupported query ID: b9d5e25dabd5f0a48f45f5b6b524bac100df05eaf5311f3e5339ac7c3dd0a37e |
|  8 | 1650656295 | https://mumbai.polygonscan.com/tx/0xa5aa8326527cd1c2976c3bc5e60556a01d2cc920f9702a646f5219bc177080db | BTC     | USD        | 39692.6      | no ✔️     No prices retrieved for AMPL/USD/VWAP Source.                                 |
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/DVM/disputable-values-monitor/src/tellor_disputables/cli.py", line 134, in main
    cli()
  File "/home/ubuntu/DVM/disputable-values-monitor/src/tellor_disputables/cli.py", line 77, in cli
    new_report = parse_new_report_event(event, poly_web3, poly_contract)
  File "/home/ubuntu/DVM/disputable-values-monitor/src/tellor_disputables/data.py", line 215, in parse_new_report_event
    disputable = is_disputable(val, query_id, CONFIDENCE_THRESHOLD)
  File "/home/ubuntu/DVM/disputable-values-monitor/src/tellor_disputables/data.py", line 108, in is_disputable
    percent_diff = (reported_val - trusted_val) / trusted_val
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

**Comment by spuddyminer** [comment]
reopened because (I think) this bug may still be a problem.
