### ISSUE TITLE
ValueError: {'code': -32000, 'message': 'unknown block'}Bug

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#20]
log: 
```|  6 | 1652370684 | https://etherscan.io/tx/0x5ec635fa4de43721a9fe206e9f4784461e6f80f934208eb680691f890bf2fd27    | ETH     | USD        | 1998.38     | no ✔️                                                                                   |
|  7 | 1652374160 | https://polygonscan.com/tx/0xd47db89347a16b48ab378a0db89c417bc8693c14a840091543ce2b19a8e5bce0 | MATIC   | USD        |    0.626823 | ❗unsupported query ID: 40aa71e5205fdc7bdb7d65f7ae41daca3820c5d3a8f62357a99eda3aa27244a3 |
|  8 | 1652375855 | https://etherscan.io/tx/0xfeb32794c662856c59328cf91d5bb970d4b97fff748fdb483235db26b794a4b0    | ETH     | USD        | 1995.6      | no ✔️                                                                                   |
|  9 | 1652385188 | https://etherscan.io/tx/0xb89c1c1bc6144c45b495ab8bc74f8de9ea9af15db98d8e977a7ae530c98c0f7c    | ETH     | USD        | 1940.74     | no ✔️               Traceback (most recent call last):                                  |
  File "<string>", line 1, in <module>
  File "/home/ubuntu/DVM/disputable-values-monitor/src/tellor_disputables/cli.py", line 134, in main
    cli()
  File "/home/ubuntu/DVM/disputable-values-monitor/src/tellor_disputables/cli.py", line 59, in cli
    event_lists = asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/DVM/disputable-values-monitor/src/tellor_disputables/data.py", line 154, in get_events
    events_lists = await asyncio.gather(
  File "/home/ubuntu/DVM/disputable-values-monitor/src/tellor_disputables/data.py", line 85, in log_loop
    events = web3.eth.get_logs({"fromBlock": num, "toBlock": num + 100, "address": addr})  # type: ignore
  File "/home/ubuntu/DVMenv/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/ubuntu/DVMenv/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/ubuntu/DVMenv/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'unknown block'}```

**Comment by spuddyminer** [comment]
So..this bug is back I think. DVM running for mumbai / rinkeby:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 134, in main
    cli()
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 59, in cli
    event_lists = asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/data.py", line 154, in get_events
    events_lists = await asyncio.gather(
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/data.py", line 85, in log_loop
    events = web3.eth.get_logs({"fromBlock": num, "toBlock": num + 100, "address": addr})  # type: ignore
  File "/home/ubuntu/env/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/ubuntu/env/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/ubuntu/env/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'unknown block'}
```

**Comment by oraclown** [comment]
Looks like an older version, bc @tallywiesenberg 's recent change made this:
```python
    events = web3.eth.get_logs({"fromBlock": num, "toBlock": num + 100, "address": addr})  # type: ignore
```
into this:
```python
    try:
        events = web3.eth.get_logs({"fromBlock": num - 100, "toBlock": "latest", "address": addr})  # type: ignore
    except ValueError as e:
    ...
```

**Comment by oraclown** [comment]
If that seems to be the case, go ahead and close this issue

**Comment by tallywiesenberg** [comment]
> So..this bug is back I think. DVM running for mumbai / rinkeby:
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 134, in main
>     cli()
>   File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 59, in cli
>     event_lists = asyncio.run(
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/data.py", line 154, in get_events
>     events_lists = await asyncio.gather(
>   File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/data.py", line 85, in log_loop
>     events = web3.eth.get_logs({"fromBlock": num, "toBlock": num + 100, "address": addr})  # type: ignore
>   File "/home/ubuntu/env/lib/python3.10/site-packages/web3/module.py", line 57, in caller
>     result = w3.manager.request_blocking(method_str,
>   File "/home/ubuntu/env/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
>     return self.formatted_response(response,
>   File "/home/ubuntu/env/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
>     raise ValueError(response["error"])
> ValueError: {'code': -32000, 'message': 'unknown block'}
> ```

I think this is from a previous version, as this traceback puts the `getLogs` call on line 85, where it is now on line 88
