### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#29]
errored out with this Traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 134, in main
    cli()
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 77, in cli
    new_report = parse_new_report_event(event, poly_web3, poly_contract)
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/data.py", line 193, in parse_new_report_event
    receipt = get_tx_receipt(tx_hash, web3, contract)
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/data.py", line 169, in get_tx_receipt
    receipt = contract.events.NewReport().processReceipt(receipt)[0]
IndexError: tuple index out of range
```

**Comment by oraclown** [comment]
Noice, want to try to fix this un, @spuddyminer ?
It would need something like:
```python
try:
    receipt = contract.events.NewReport().processReceipt(receipt)[0]
# except the specific error here
    # add a logging message
    # return None
```
Then update the return type for the function to be `-> Optional[whatever it usually returns]` and you'll have to import `Optional` from `typing` if it ain't already

If your plate's too full, just assign sir @tallywiesenberg
