### ISSUE TITLE
ImportError: cannot import name 'SpotPrice' from 'telliot_core.api' 

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#31]
the disputable-values-monitor currently fails to start with a fresh install. full traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 15, in <module>
    from tellor_disputables.data import get_contract
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/data.py", line 12, in <module>
    from telliot_core.api import SpotPrice
ImportError: cannot import name 'SpotPrice' from 'telliot_core.api' (/home/ubuntu/env2/lib/python3.10/site-packages/telliot_core/api.py)
```

**Comment by tallywiesenberg** [comment]
Closed #27
