### ISSUE TITLE
Uncaught Exception: `Asset not supported: XBT`

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/disputable-values-monitor#37]
Pulled from main (fresh install), using python3.10
```sh
m1 ➜  disputable-values-monitor (main) ✗ poetry run cli           
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tallywiesenberg/Downloads/disputable-values-monitor/src/tellor_disputables/cli.py", line 134, in main
    asyncio.run(cli())
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/tallywiesenberg/Downloads/disputable-values-monitor/src/tellor_disputables/cli.py", line 75, in cli
    new_report = await parse_new_report_event(event, eth_web3, eth_contract)
  File "/Users/tallywiesenberg/Downloads/disputable-values-monitor/src/tellor_disputables/data.py", line 244, in parse_new_report_event
    disputable = await is_disputable(val, query_id, CONFIDENCE_THRESHOLD)
  File "/Users/tallywiesenberg/Downloads/disputable-values-monitor/src/tellor_disputables/data.py", line 128, in is_disputable
    trusted_val, _ = await general_fetch_new_datapoint(current_feed)
  File "/Users/tallywiesenberg/Downloads/disputable-values-monitor/src/tellor_disputables/data.py", line 114, in general_fetch_new_datapoint
    return await feed.source.fetch_new_datapoint()
  File "/Users/tallywiesenberg/Downloads/disputable-values-monitor/.venv/lib/python3.10/site-packages/telliot_feeds/sources/price_aggregator.py", line 78, in fetch_new_datapoint
    datapoints = await self.update_sources()
  File "/Users/tallywiesenberg/Downloads/disputable-values-monitor/.venv/lib/python3.10/site-packages/telliot_feeds/sources/price_aggregator.py", line 64, in update_sources
    inputs = await gather_inputs()
  File "/Users/tallywiesenberg/Downloads/disputable-values-monitor/.venv/lib/python3.10/site-packages/telliot_feeds/sources/price_aggregator.py", line 61, in gather_inputs
    datapoints = await asyncio.gather(*[source.fetch_new_datapoint() for source in sources])
  File "/Users/tallywiesenberg/Downloads/disputable-values-monitor/.venv/lib/python3.10/site-packages/telliot_feeds/pricing/price_source.py", line 32, in fetch_new_datapoint
    datapoint = await self.service.get_price(self.asset, self.currency)
  File "/Users/tallywiesenberg/Downloads/disputable-values-monitor/.venv/lib/python3.10/site-packages/telliot_feeds/sources/price/spot/kraken.py", line 38, in get_price
    raise Exception(f"Asset not supported: {asset}")
Exception: Asset not supported: XBT
```

**Comment by oraclown** [comment]
So some exchanges like Kraken use `XBT` as the symbol for bitcoin. See "Code" section [here](https://en.wikipedia.org/wiki/Bitcoin). To close this issue:
- auto-replace XBT with BTC or make sure it fetches the Kraken spot price source. Test this behavior
- handle any further assets not supported so the monitor doesn't halt/quit. Test this behavior
