### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#42]
Disputable-values-monitor error out with the following traceback: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 134, in main
    asyncio.run(cli())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/cli.py", line 77, in cli
    new_report = await parse_new_report_event(event, poly_web3, poly_contract)
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/data.py", line 244, in parse_new_report_event
    disputable = await is_disputable(val, query_id, CONFIDENCE_THRESHOLD)
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/data.py", line 128, in is_disputable
    trusted_val, _ = await general_fetch_new_datapoint(current_feed)
  File "/home/ubuntu/disputable-values-monitor/src/tellor_disputables/data.py", line 114, in general_fetch_new_datapoint
    return await feed.source.fetch_new_datapoint()
  File "/home/ubuntu/env3/lib/python3.10/site-packages/telliot_feeds/sources/price_aggregator.py", line 78, in fetch_new_datapoint
    datapoints = await self.update_sources()
  File "/home/ubuntu/env3/lib/python3.10/site-packages/telliot_feeds/sources/price_aggregator.py", line 64, in update_sources
    inputs = await gather_inputs()
  File "/home/ubuntu/env3/lib/python3.10/site-packages/telliot_feeds/sources/price_aggregator.py", line 61, in gather_inputs
    datapoints = await asyncio.gather(*[source.fetch_new_datapoint() for source in sources])
  File "/home/ubuntu/env3/lib/python3.10/site-packages/telliot_feeds/pricing/price_source.py", line 32, in fetch_new_datapoint
    datapoint = await self.service.get_price(self.asset, self.currency)
  File "/home/ubuntu/env3/lib/python3.10/site-packages/telliot_feeds/sources/price/spot/coinmarketcap.py", line 68, in get_price
    price = data["data"][asset]["quote"][currency]["price"]
KeyError: 'data'
```

**Comment by tallywiesenberg** [comment]
Closed with issue https://github.com/tellor-io/telliot-feeds/pull/395
